### ISSUE TITLE
Manifest unknown after cleaning up untagged Docker images

### ISSUE THREAD

**Issue by kkalev** [Chizkiyahu/delete-untagged-ghcr-action#45]
We are facing `manifest unknown` messages from GHCR after running a cleanup of untagged Docker images in our public and private repos.

The github action we implemented was as follows:
```
name: clean-untagged
run-name: Clean untagged GHCR Docker images
on:
  workflow_dispatch:
  schedule:
    - cron: 15 2 * * 0
jobs:
  clean-untagged:
    runs-on: ubuntu-latest
    steps:
      - name: Delete untagged ghcr
        uses: Chizkiyahu/delete-untagged-ghcr-action@v4.0.1
        with:
          token: ${{ secrets.GHCR_TOKEN }}
          untagged_only: true
          owner_type: 'org'
```

The GHCR_TOKEN is a PAT with read and write package permissions. The PAT belongs to an org admin.

After running the action (we had to run it twice to delete all untagged images from all our repos) we only observed tagged Docker images as expected. Yet after trying to `docker pull` any Docker image created from our repos (private and public) we got an error `manifest unknown`. The same for `docker manifest inspect`. It looks like the manifests were not part of the tagged Docker image versions.

Even if we browse the packages for a repo and copy paste the sha2 hash of the `latest` version `docker manifest inspect` will fail:
```
# docker manifest inspect ghcr.io/<org>/<repo>:latest@sha256:c4af81d78998657f15bc61ba02d44edd98c941becaa0027033798ceb06fb154b
manifest unknown
```

A new build/push (using github actions) allows us to pull images and manifests without any problems.

Any help will be appreciated.
